name: empty-spigot-plugin
version: @version@
description: An empty example plugin for Spigot with Gradle
main: net.javaforge.minecraft.spigot.plugin.EmptySpigotPlugin

commands:
  hello:
    description: say hello to the user
  tp:
    description: teleport to the spawn